spawnlocation:
  x: 0
  y: 0
  z: 0
messages:
  messageReceived: "§e%sender% §7-> §e%receiver%§f:>"
  messageReceivedServeradmin: "§7Der §eServeradmin §7hat dir eine Nachricht gesendet§f:> "
  messageReceiverNotOnline: "§cDieser Spieler ist derzeit nicht online!"
  messageSent: "§e%sender% §7-> §e%receiver%§f:>"
  messageSamePlayer: "§7Wie einsam muss man sein, um zu versuchen, sich selbst eine Nachricht zu senden?"
  messageTooFewArguments: "§cSyntax: /msg <Empfänger> <Nachricht>"
ping:
  message: "§7Dein Ping beträgt derzeit %ping% ms."
setspawn:
  message: "§7Der Spawn wurde erfolgreich neu gesetzt!"
  messageSyntax: "§cSyntax: /setspawn [<x> <y> <z>]"
spawn:
  message: "§7Du wurdest erfolgreich an den Spawn teleportiert!"
tpa:
  requestSent: "§7Die Anfrage an §e%player% §7wurde gesendet!"
  prompt: "§e%player% §7möchte sich zu dir teleportieren! Du kannst die Anfrage mit /tpaccept §7annehmen."
  teleportationSuccessful: "§e%player% §7wurde erfolgreich zu dir teleportiert"
  messageSyntax: "§cSyntax: /tpa <Empfänger>"
tpaccept:
  teleportationSuccessful: "§7Du wurdest erfolgreich zu §e%player% §7teleportiert"
  requestNotFound: "§cDie Anfrage von §e%player% §cwurde nicht gefunden!"
  messageSyntax: "§cSyntax: /tpaccept <Absender>"
tpdeny:
  messageSyntax: "§cSyntax: /tpdeny <Absender>"
home:
  noHomeFound: "§cDu hast keinen Homepunkt gesetzt!"
  teleportationSuccessful: "§7Du wurdest erfolgreich nach Hause teleportiert!"
  messageSyntax: "§cSyntax: /home"
sethome:
  message: "§7Dein Homepunkt wurde erfolgreich gesetzt!"
  messageSyntax: "§cSyntax: /sethome"
  messageSyntaxOp: "§cSyntax /sethome [[world] x y z]"
joinEvent:
  message: "§7[§a+§7] §e%player%"
quitEvent:
  message: "§7[§4-§7] §e%player%"
chat:
  prefix: "§e%player%§7:> "
settings:
  messageSyntax: "§c/settings [flag true/false]"
  messageSuccessful: "§7Die Einstellung wurde erfolgreich übernommen!"
  guiTitle: "Benutzereinstellungen"
  noteOnChatTitleActive: "§bBenachrichtigungston §cdeaktivieren"
  noteOnChatTitleActiveLore: "§7Deaktiviert den Benachrichtigungston, den du hörst, &break;§7wenn dein Name im Chat erwähnt wird."
  noteOnChatTitleInactive: "§bBenachrichtigungston §aaktivieren"
  noteOnChatTitleInactiveLore: "§7Aktiviert den Benachrichtigungston, den du hörst, &break;§7wenn dein Name im Chat erwähnt wird."
  info:
    message: "§7Folgende Daten wurden über Dich abgespeichert:"
    username: "§eNutzername"
    usernameHover: "§7Diese Information wird in der Datenbank gespeichert."
    uuid: "§eMinecraft-UUID"
    uuidHover: "§7Diese Information wird nicht dauerhaft gespeichert, aber verarbeitet."
    nickname: "§eAnzeigename"
    nicknameHover: "§7Diese Information wird dauerhaft gespeichert."
    ip: "§eIP-Adresse"
    ipHover: "§7Diese Information wird in den Server-Logs gespeichert und vom Server zu Betriebszwecken verarbeitet."
    noteOnChat: "§eBenachrichtigungston"
    noteOnChatHover: "§7Diese Information wird in der Datenbank gespeichert."
    home: "§eHome-Location"
    homeHover: "§7Diese Information wird in der Datenbank gespeichert."
    homeInfo: "§7Welt: %world% X: %X% Y: %Y% Z: %Z%"
    noHomeSet: "§7Es ist kein Homepunkt gesetzt."
    onFalse: "§4Deaktiviert"
    onTrue: "§aAktiviert"
    colon: "§8:§7 "
nickname:
  message: "§7Der Nickname von §e%player% §7wurde erfolgreich zu §e%nickname% §7geändert!"
  messageSyntax: "/nickname <Spielername> <Nickname>"
resetnickname:
  message: "§7Der Nickname von §e%player% §7wurde erfolgreich zurückgesetzt!"
  messageSyntax: "§cSyntax: /resetnickname <Spielername>"
colonCommand:
  message: "§cDas darfst du nicht!"
plugin:
  message: "§cDas darfst du nicht!"
groups:
  messageGroupNotFound: "§cDie gewünschte Gruppe konnte nicht gefunden werden."
  messagePlayerNotFound: "§cDer gewünschte Spieler konnte nicht gefunden werden."
  messageGroupAlreadyExists: "§cDiese Gruppe existiert bereits!"
  messagePlayerAlreadyInGroup: "§cDieser Spieler ist bereits Mitglied der Gruppe."
  messageRemoveOwner: "§cDer Besitzer einer Gruppe darf nicht aus ihr entfernt werden!"
  messageList: "§7Die folgenden Gruppen wurden gefunden:"
  messageListMembers: "§7Die folgenden Gruppenmitglieder wurden gefunden:"
  messageSuccessfullyLeft: "§7Du bist erfolgreich aus der Gruppe §9%groupTag% §7ausgetreten!"
  messageSuccessfullyJoined: "§7Du wurdest erfolgreich zur Gruppe §9%groupTag% §7hinzugefügt!"
  messageSuccessfullyAddedGroup: "§7Die Gruppe §9%groupTag% §7 wurde erfolgreich erstellt!"
  messageSuccessfullyRemovedMember: "§7Der Spieler §e%player% §7wurde erfolgreich von der Gruppe §9%groupTag% §7entfernt!"
  messageSuccessfullyRemovedGroup: "§7Die Gruppe §9%groupTag% §7 wurde erfolgreich gelöscht!"
  messageRequestAccepted: "§e%player% §7hat deine Anfrage zum Beitritt in die Gruppe %groupTag% angenommen!"
  noPermissionForGroup: "§cDu hast keine Erlaubnis diese Gruppe zu verändern!"
  requestSent: "§7Die Anfrage an §e%player% §7wurde gesendet!"
  groupPrompt: "§e%player% §7möchte dich zur Gruppe §9%groupTag% §7hinzufügen! Du kannst die Anfrage mit %command% §7annehmen."
  prefix: "§7[§9%group%§7] §e%sender%§7:> "
  bullet: "§7- §9"
  help:
    message:
      - "§7Hier findest du alle Optionen des Befehls /group:"
      - "§e/group list§7: Zeigt alle Gruppen an, in denen du Mitglied bist"
      - "§e/group leave <Gruppenname>§7: Verlasse eine Gruppe"
      - "§e/group add <Gruppenname>§7: Erstellt eine neue Gruppe"
      - "§e/group remove <Gruppenname>§7: Löscht eine Gruppe"
      - "§e/group member add <Nutzername> <Gruppenname>§7: Fügt einen Spieler zu einer Gruppe hinzu"
      - "§e/group member remove <Nutzername> <Gruppenname>§7: Entfernt einen Spieler aus einer Gruppe"
      - "§e/group listmembers <Gruppenname>§7: Listet alle Mitglieder einer Gruppe auf."


